site_name: Cancer Prediction
site_url: https://github.com/swm35/cancer-prediction-swm35
repo_url: https://github.com/swm35/cancer-prediction-swm35
nav:
  - Home: index.md
  - cancer-prediction:
    - cancer model: cancer-prediction/cancer_model.md
    - streamlit app: cancer-prediction/streamlit_app.md
theme: readthedocs
plugins:
  - mkdocstrings
watch:
  - .  # reload docs for file changes
